configfile: "config/config.yaml"

DONORS = config["pbmc"].keys()

rule all:
    input:
        expand("data/raw/{donor}/fastqs.done", donor=DONORS)

rule download_fastqs:
    output:
        tar="data/raw/{donor}/fastqs.tar",
        done="data/raw/{donor}/fastqs.done"
    params:
        url=lambda wc: config["pbmc"][wc.donor]["url"]
    shell:
        """
		set -euo pipefail
        mkdir -p data/raw/{wildcards.donor}
        wget -c -O {output.tar} {params.url}
        tar -xvf {output.tar} -C data/raw/{wildcards.donor}
        touch {output.done}
        """
